{
 "title": "Admin dashboard-JJ",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jenkins ready to receive requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "default_jenkins_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_count_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jenkins_job_count_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time Jenkins machine initialized",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "default_jenkins_uptime / 3600", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_count_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_count_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Application Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "default_jenkins_version_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_execution_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jenkins_task_execution_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins in quiet mode",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "default_jenkins_quietdown", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_execution_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_task_execution_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes loaded in JVM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_classes_currently_loaded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_waiting_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "jenkins_job_waiting_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Classes loaded since JVM started execution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_classes_loaded_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_waiting_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_waiting_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes unloaded since JVM started execution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_classes_unloaded_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_total_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "jenkins_job_total_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM current thread count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_total_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_total_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM daemon thread count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_daemon", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_queue_pending_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_pending_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM peak thread count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_peak", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_responseCodes_badRequest_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_badRequest_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM started thread count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_started_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_activeRequests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_activeRequests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM threads deadlocked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_deadlocked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_runs_aborted_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_aborted_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM threads deadlock waiting to acquire object monitors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_deadlocked_monitor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_health_check_duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    { "expr": "jenkins_health_check_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM threads current count by state",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    { "expr": "jvm_threads_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_health_check_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_health_check_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM objects waiting in finalizer queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_objects_pending_finalization",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_executor_in_use_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_in_use_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used bytes in JVM memory area",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_queue_buildable_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_buildable_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Committed bytes in JVM memory area",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_bytes_committed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_scheduled_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_task_scheduled_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max bytes in JVM memory area",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_bytes_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_count_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    { "expr": "jenkins_project_count_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Initial bytes given to JVM memory area",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_bytes_init", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_count_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_count_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_executor_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Committed bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_runs_success_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_pool_bytes_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_plugins_inactive",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_inactive", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Initial bytes given JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_memory_pool_bytes_init", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_node_offline_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "targets": [
    { "expr": "jenkins_node_offline_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_collection_used_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_node_offline_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_offline_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Committed bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_collection_committed_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system_cpu_load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_collection_max_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_node_count_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "targets": [
    { "expr": "jenkins_node_count_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Initial bytes JVM memory pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_collection_init_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_node_count_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_count_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used bytes JVM buffer pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_buffer_pool_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_responseCodes_serverError_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serverError_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes capacity JVM buffer pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_buffer_pool_capacity_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_enabled_count_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used buffers JVM buffer pool",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_buffer_pool_used_buffers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_enabled_count_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_enabled_count_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Executors Available",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_available{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_size_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "targets": [
    { "expr": "jenkins_queue_size_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jenkins Executors Busy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_busy{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_size_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 248 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_size_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Executors Connecting",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 256 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_connecting{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_runs_not_built_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 256 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_not_built_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jenkins Executors Defined",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 264 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_defined{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_building_duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 264 },
   "targets": [
    { "expr": "jenkins_job_building_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jenkins Executors Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 272 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_idle{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_building_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 272 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_building_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins Executors Online",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 280 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_online{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_stuck_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 280 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_stuck_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jenkins Executors Queue Length",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 288 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_executors_queue_length{label=\"built-in\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_node_online_history",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 288 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_online_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_total_used_window_1h",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_memory_total_used_window_1h", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_node_online_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 296 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_online_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_total_used_window_1h_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 304 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_total_used_window_1h_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 304 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_queue_blocked_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 312 },
   "targets": [
    { "expr": "jenkins_queue_blocked_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_queue_pending_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 312 },
   "targets": [
    { "expr": "jenkins_queue_pending_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_queue_blocked_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 320 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_blocked_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_pending_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 320 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_pending_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_pools_Metaspace_used_window_1h",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 328 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Metaspace_used_window_1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_task_queuing_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 328 },
   "targets": [
    { "expr": "jenkins_task_queuing_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_Metaspace_used_window_1h_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 336 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Metaspace_used_window_1h_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_task_queuing_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 336 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_task_queuing_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_pools_Compressed_Class_Space_usage_x100_history",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 344 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Compressed_Class_Space_usage_x100_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_buildable_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 344 },
   "targets": [
    {
     "expr": "jenkins_queue_buildable_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_pools_Compressed_Class_Space_usage_x100_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 352 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Compressed_Class_Space_usage_x100_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_buildable_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 352 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_buildable_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_pools_Metaspace_usage_x100_history",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 360 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Metaspace_usage_x100_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_blocked_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 360 },
   "targets": [
    { "expr": "jenkins_job_blocked_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_Metaspace_usage_x100_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 368 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Metaspace_usage_x100_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_blocked_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 368 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_blocked_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system_cpu_load_x100_window_15m",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_x100_window_15m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_responseCodes_noContent_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_noContent_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system_cpu_load_x100_window_15m_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 384 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_load_x100_window_15m_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_runs_total_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 384 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_total_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_G1_Survivor_Space_used_window_1h",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 392 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_G1_Survivor_Space_used_window_1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_plugins_active",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 392 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_G1_Survivor_Space_used_window_1h_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 400 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_G1_Survivor_Space_used_window_1h_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_buildable_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 400 },
   "targets": [
    { "expr": "jenkins_job_buildable_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_Metaspace_usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 408 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_Metaspace_usage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_job_buildable_duration_count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 408 },
   "targets": [
    {
     "expr": "jenkins_job_buildable_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_memory_pools_CodeHeap__profiled_nmethods__committed_window_5m",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 416 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_CodeHeap__profiled_nmethods__committed_window_5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_stuck_history",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 416 },
   "targets": [
    { "expr": "jenkins_queue_stuck_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_CodeHeap__profiled_nmethods__committed_window_5m_count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 424 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_CodeHeap__profiled_nmethods__committed_window_5m_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_stuck_history_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 424 },
   "targets": [
    {
     "expr": "jenkins_queue_stuck_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_runs_unstable_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 432 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_unstable_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_queuing_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 432 },
   "targets": [
    { "expr": "jenkins_job_queuing_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_plugins_failed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 440 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_plugins_failed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_queuing_duration_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 440 },
   "targets": [
    {
     "expr": "jenkins_job_queuing_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 448 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_averageDepth",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 448 },
   "targets": [
    { "expr": "jenkins_job_averageDepth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_terminated_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 456 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_terminated_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_runs_failure_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 456 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_runs_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vm_memory_pools_CodeHeap__non_profiled_nmethods__used_window_5m",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 464 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_memory_pools_CodeHeap__non_profiled_nmethods__used_window_5m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_task_buildable_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 464 },
   "targets": [
    {
     "expr": "jenkins_task_buildable_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_cpu_load_x100_history",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 472 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_cpu_load_x100_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_buildable_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 472 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_task_buildable_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vm_cpu_load_x100_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 480 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vm_cpu_load_x100_history_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_node_offline_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 480 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_offline_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 488 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{runtime=\"OpenJDK Runtime Environment\",vendor=\"Eclipse Adoptium\",version=\"17.0.17+10\",}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_health_check_score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 488 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_score", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds_count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 496 },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_task_waiting_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 496 },
   "targets": [
    { "expr": "jenkins_task_waiting_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds_sum",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 504 },
   "targets": [
    { "expr": "jvm_gc_collection_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_waiting_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 504 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_task_waiting_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 512 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_disabled_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 512 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_open_fds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 520 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_health_check_inverse_score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 520 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_health_check_inverse_score",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_max_fds",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 528 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_max_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_node_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 528 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_count_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 536 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_disabled_count_history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 536 },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_resident_memory_bytes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 544 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_project_disabled_count_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 544 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_project_disabled_count_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 552 },
   "targets": [
    {
     "expr": "vm_cpu_load{job=\"jenkins\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_queue_size_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 552 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_queue_size_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_executor_count_history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 560 },
   "targets": [
    { "expr": "jenkins_executor_count_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_node_online_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 568 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_node_online_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_health_check_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 576 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_health_check_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_executor_free_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 584 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_executor_free_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_execution_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 592 },
   "targets": [
    { "expr": "jenkins_job_execution_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_execution_time_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 600 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_job_execution_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_task_blocked_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 608 },
   "targets": [
    { "expr": "jenkins_task_blocked_duration", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_task_blocked_duration_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 616 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_task_blocked_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_responseCodes_notModified_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 624 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_notModified_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_responseCodes_notFound_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 632 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_notFound_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_project_count_value",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 640 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_project_count_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_job_scheduled_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 648 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jenkins_job_scheduled_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_executor_in_use_history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 656 },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_history",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_executor_in_use_history_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 664 },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jenkins_executor_free_history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 672 },
   "targets": [
    { "expr": "jenkins_executor_free_history", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jenkins_executor_free_history_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 680 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_free_history_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_responseCodes_forbidden_total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 688 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_forbidden_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}