{
 "title": "Jenkins – Builds",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": {
     "query": "label_values(default_jenkins_builds_total_build_count_total, repo)"
    }
   },
   {
    "name": "jenkins_job",
    "query": {
     "query": "label_values(default_jenkins_builds_total_build_count_total{repo=~\"$repo\"}, jenkins_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Aborted Builds",
   "type": "timeseries",
   "description": "Aborted Builds (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_aborted_build_count_created{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Job Health Score",
   "type": "timeseries",
   "description": "Job Health Score",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Failed Builds (Created)",
   "type": "timeseries",
   "description": "Failed Builds (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_failed_build_count_created{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Discard Active Builds",
   "type": "timeseries",
   "description": "Discard Active Builds",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "default_jenkins_builds_discard_active{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Build Duration Summary (Count)",
   "type": "timeseries",
   "description": "Build Duration Summary (Count)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "default_jenkins_builds_duration_milliseconds_summary_count{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Result",
   "type": "timeseries",
   "description": "Last Build Result",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Job Log Updated",
   "type": "timeseries",
   "description": "Job Log Updated",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "default_jenkins_builds_job_log_updated{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Build Duration Summary (Sum)",
   "type": "timeseries",
   "description": "Build Duration Summary (Sum)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "default_jenkins_builds_duration_milliseconds_summary_sum{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Failed Builds (Total)",
   "type": "timeseries",
   "description": "Failed Builds (Total)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "default_jenkins_builds_failed_build_count_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Tests Total",
   "type": "timeseries",
   "description": "Last Build Tests Total",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_tests_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Result (Ordinal)",
   "type": "timeseries",
   "description": "Last Build Result (Ordinal)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_result_ordinal{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Duration (ms)",
   "type": "timeseries",
   "description": "Last Build Duration (ms)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_duration_milliseconds{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Log Size (Bytes)",
   "type": "timeseries",
   "description": "Last Build Log Size (Bytes)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_logfile_size_bytes{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Stage Duration (Count)",
   "type": "timeseries",
   "description": "Last Stage Duration (Count)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_count{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Waiting Time (Minutes)",
   "type": "timeseries",
   "description": "Last Build Waiting Time (Minutes)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_waiting_milliseconds{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}\n/ 1000 / 60\n"
    }
   ]
  },
  {
   "title": "Last Build Start Time (Minutes)",
   "type": "timeseries",
   "description": "Last Build Start Time (Minutes)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "(time() * 1000\n - default_jenkins_builds_last_build_start_time_milliseconds{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"})\n/ 1000 / 60"
    }
   ]
  },
  {
   "title": "Last Build Tests Failing",
   "type": "timeseries",
   "description": "Last Build Tests Failing",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_build_tests_failing{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Running Build Duration (minutes)",
   "type": "timeseries",
   "description": "Running Build Duration (minutes)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "default_jenkins_builds_running_build_duration_milliseconds{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}\n/ 1000 / 60\n"
    }
   ]
  },
  {
   "title": "Last Stage Duration (Created)",
   "type": "timeseries",
   "description": "Last Stage Duration (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_created{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Tests Skipped",
   "type": "timeseries",
   "description": "Last Build Tests Skipped",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_last_build_tests_skipped{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Build Likely Stuck",
   "type": "timeseries",
   "description": "Last Build Likely Stuck",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_likely_stuck{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Total Builds (Total)",
   "type": "timeseries",
   "description": "Total Builds (Total)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "default_jenkins_builds_total_build_count_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Successful Builds (Created)",
   "type": "timeseries",
   "description": "Successful Builds (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_created{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Stage Duration (Sum)",
   "type": "timeseries",
   "description": "Last Stage Duration (Sum)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_duration_milliseconds_summary_sum{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Last Stage Result (Ordinal)",
   "type": "timeseries",
   "description": "Last Stage Result (Ordinal)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "default_jenkins_builds_last_stage_result_ordinal{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Unstable Builds (Created)",
   "type": "timeseries",
   "description": "Unstable Builds (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "default_jenkins_builds_unstable_build_count_created{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Successful Builds (Total)",
   "type": "timeseries",
   "description": "Successful Builds (Total)",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Unstable Builds (Total)",
   "type": "timeseries",
   "description": "Unstable Builds (Total)",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "default_jenkins_builds_unstable_build_count_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  },
  {
   "title": "Total Builds (Created)",
   "type": "timeseries",
   "description": "Total Builds (Created)",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total{repo=~\"$repo\", jenkins_job=~\"$jenkins_job\"}"
    }
   ]
  }
 ]
}