{
 "title": "Jenkins HTTP Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Success Rate(Last 5 minutes)",
   "type": "stat",
   "description": "HTTP Success Rate",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_ok_total[5m])"
    }
   ]
  },
  {
   "title": "Client Errors(Last 5 minutes)",
   "type": "gauge",
   "description": "Client Errors",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_badRequest_total[5m])"
    }
   ]
  },
  {
   "title": "Jenkins internal errors(http: 5xx)",
   "type": "gauge",
   "description": "Plugin crash, JVM errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serverError_total"
    }
   ]
  },
  {
   "title": "Jenkins temporarily unavailable(http: 503)",
   "type": "gauge",
   "description": "Restart, overload, GC pause",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_serviceUnavailable_total"
    }
   ]
  },
  {
   "title": "Resource not found(http: 404)",
   "type": "gauge",
   "description": "Deleted jobs, wrong URLs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_notFound_total"
    }
   ]
  },
  {
   "title": "Authorization failures(http: 403)",
   "type": "gauge",
   "description": "User lacks permission, bad token",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_forbidden_total"
    }
   ]
  },
  {
   "title": "Invalid client requests(http: 400)",
   "type": "gauge",
   "description": "Malformed API calls, bad webhook payload",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_badRequest_total"
    }
   ]
  },
  {
   "title": "Cached content reused(http: 304)",
   "type": "gauge",
   "description": "Browser reload of UI assets",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_notModified_total"
    }
   ]
  },
  {
   "title": "Success with no response body(http: 204)",
   "type": "gauge",
   "description": "API updates",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_noContent_total"
    }
   ]
  },
  {
   "title": "Resources successfully created(http: 201)",
   "type": "gauge",
   "description": "Job creation, build trigger via API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_responseCodes_created_total"
    }
   ]
  },
  {
   "title": "Successful HTTP responses",
   "type": "gauge",
   "description": "Should be highest; indicates healthy Jenkins",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_responseCodes_ok_total" }
   ]
  },
  {
   "title": "Total HTTP requests received",
   "type": "gauge",
   "description": "UI access, API calls, webhooks, Prometheus scrape",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_count" }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Active Requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_activeRequests" }
   ]
  },
  {
   "title": "Service Unavailable(Last 5 minutes)",
   "type": "gauge",
   "description": "Service Unavailable",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_serviceUnavailable_total[5m])"
    }
   ]
  },
  {
   "title": "Server Errors(Last 5 minutes)",
   "type": "gauge",
   "description": "Server Errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_serverError_total[5m])"
    }
   ]
  },
  {
   "title": "Other HTTP codes (302, 401, 429)",
   "type": "gauge",
   "description": "Redirects, unauthorized access",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_responseCodes_other_total" }
   ]
  }
 ]
}