{
 "title": "Jenkins Jobs Stats",
 "description": "Creates some charts based on data from https://plugins.jenkins.io/prometheus/",
 "tags": [
  "jenkins",
  "prometheus"
 ],
 "time": { "from": "2022-03-27T17:38:22.304Z", "to": "2022-03-31T09:36:39.813Z" },
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": {
     "query": "label_values(jenkins_queue_size_history,quantile)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes Count (Stack)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    { "expr": "jenkins_node_online_value", "legendFormat": "online" },
    { "expr": "jenkins_node_offline_value", "legendFormat": "offline" }
   ]
  },
  {
   "title": "Executors (Stack)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    { "expr": "jenkins_executor_in_use_value", "legendFormat": "in use" },
    { "expr": "jenkins_executor_free_value", "legendFormat": "free" }
   ]
  },
  {
   "title": "Jobs Scheduling Rate (per min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(jenkins_job_scheduled_total[60m]) / 60"
    }
   ]
  },
  {
   "title": "Queue (Stack)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "jenkins_queue_blocked_value", "legendFormat": "blocked" },
    { "expr": "jenkins_queue_buildable_value", "legendFormat": "buildable" },
    { "expr": "jenkins_queue_pending_value", "legendFormat": "pending" },
    { "expr": "jenkins_queue_stuck_value", "legendFormat": "stuck" }
   ]
  },
  {
   "title": "Executors Queue Length per Label (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "default_jenkins_executors_queue_length{}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Executors Defined per Label (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "default_jenkins_executors_defined{}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Executors Defined but not Online per Label",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "default_jenkins_executors_defined{} - default_jenkins_executors_online{}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Executors Idle per Label (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "default_jenkins_executors_idle{}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Average Last Build Duration by Repo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg by (repo) (default_jenkins_builds_last_build_duration_milliseconds{})",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Executors Busy per Label (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "default_jenkins_executors_busy{}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Failed Builds Ratio by Repo (Stack)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (repo) (rate(default_jenkins_builds_failed_build_count_total{}[$__rate_interval])) / (sum by (repo) (rate(default_jenkins_builds_success_build_count_total{}[$__rate_interval])) + sum by (repo) (rate(default_jenkins_builds_failed_build_count_total{}[$__rate_interval])))",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}